#################################
# Official Jekyll documentation #
#################################

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


#######################################################
# Config you may need to change once per semester     #
#######################################################

# - Jekyll default variables.
# - For the title on the homepage, the name people see in the browser tab, etc.
title: "Course Name"
description: "Course Name at School Name"

# - Jekyll default variable.
# - The subpath of your site, e.g. /blog
# - Example: If you build your site to inst.eecs.berkeley.edu/~cs188/sp25,
#   then this should say "/~cs188/sp25"
# - Example: If you build your site to sp25.cs161.org,
#   then this should say "" since there is no subpath
baseurl: ""

# - Jekyll default variable.
# - The full URL of your homepage.
url: "https://template.cs161.org"

# - Used in _includes/title.html
# - Path to an image to display in the sidebar (or top bar on mobile). Leave blank to omit.
logo: '/assets/images/logo.png'

# - Used in _includes/title.html
# - Optional text that replaces site.title at the top of the sidebar when set.
# - If logo is set and shorthand_text is left blank, the logo will take up 100% of the space.
shorthand_text: 'Course Name'

# - Can be used throughout the website (e.g. project specs).
# - Example: In the spec, write "Pull from the skeleton-{{ site.semester_slug }} repo."
#   This will automatically update to "skeleton-fa24" or "skeleton-sp25" each semester.
semester_slug: sp25
semester_full: Spring 2025

# - Updates the top line of the homepage, i.e. the one that says
#   "Instructor: EvanBot / Lecture: TuTh, 12:30–2:00 PM, Wheeler 150 [Zoom, Playlist]"
# - Note: Instructor is pulled from the _staffers folder.
lecture:
  time: "TuTh, 12:30–2:00 PM"
  location:
      name: "Wheeler 150"
      link: ""
heading_links:
  - text: "Zoom"
    url: "https://berkeley.zoom.us"
  - text: "Playlist"
    url: "https://www.youtube.com/playlist?list=PLp8QV47qJEg4fg0UAZzU2FeuZrs6XMjkK"

# - Used on staff.md to show students the staff email.
staff_email: "evanbot@berkeley.edu"

# - Use this to show/hide the "announcements" feature on the homepage.
# - Add your weekly announcements in the _announcements folder.
enable_announcements: true


#######################################################
# Config to show/hide warnings on pages               #
#######################################################

# - Set this to true at the start of semesters to show a warning on every page.
under_construction: false

# - Set this to true in the first few weeks of the semester
#   if discussion times are uncertain (populates on calendar.md only).
discussions_under_construction: false

# - Set this to true to archive the semester and show a warning on every page.
outdated: false

# - If you set outdated, what is the latest site URL that we should link to?
# - Ideally this is a URL that always redirects to your current semester, e.g.
#   https://cs161.org or https://inst.eecs.berkeley.edu/~cs188
# - This is only used in _layouts/page.html and _layouts/project.html.
latest_sem: "https://template.cs161.org"


#######################################################
# Config for external links in the top-right corner   #
#######################################################

# - Leave "Dark Mode" unchanged. It uses Javascript to toggle dark mode.

aux_links:
  Dark Mode:
    - '#'
  Ed:
    - 'https://edstem.org'
  OH Queue:
    - 'https://oh.cs161.org'
  Source Code on GitHub:
    - 'https://github.com/cs161-staff/course-site-template'


#######################################################
# Config to show colored callout blocks on pages      #
#######################################################

# - See official JTD for documentation:
# - https://just-the-docs.com/docs/ui-components/callouts/
# - https://just-the-docs.com/docs/configuration/#callouts

callouts:
  warning:
    title: Warning
    color: yellow
  info:
    title: Info
    color: purple
  tip:
    title: Tip
    color: green
  task:
    title: Task
    color: blue
  danger: 
    title: Danger
    color: red
  story: # CS 161 custom config for story
    title: Story
    color: blue


#######################################################
# Config you will probably never need to change,      #
# unless you are rebuilding the website               #
#######################################################

# - If you have files that should not be built on the website, list them here.
# - Example: Your project spec has a README that's for staff editing the spec.
# - Example: You have a Python script you use to automate something in the repo.
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "vendor", "README.md"]

# - Every few years, we may need to update the JTD version to pull from upstream.
remote_theme: just-the-docs/just-the-docs@v0.8.2

color_scheme: wider
search_enabled: true
heading_anchors: true
enable_copy_code_button: true
permalink: pretty
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/staff/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag